python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 1024
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 2048
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 4096
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 8192
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 1024
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 2048
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 4096
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset ogbn_arxiv0 --n_epochs 100 --batch_size 8192
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset reddit0 --n_epochs 100 --batch_size 1024
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset reddit0 --n_epochs 100 --batch_size 2048
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset reddit0 --n_epochs 100 --batch_size 4096
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 0 --dataset reddit0 --n_epochs 100 --batch_size 8192
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset reddit0 --n_epochs 100 --batch_size 1024
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset reddit0 --n_epochs 100 --batch_size 2048
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset reddit0 --n_epochs 100 --batch_size 4096
python3 clients_start.py --model_name gcn --sampling 2 --run_client_idx 7 --dataset reddit0 --n_epochs 100 --batch_size 8192
