# Set the IP addresses of the servers to deploy the cluster
# WARNING: rewrite cache_group item in ./dist/conf/static_cache.yaml
cluster_servers:
  - "10.214.243.19"
  - "10.214.241.227"
#  - "10.214.241.228"
#  - "10.214.241.229"

# sshinfo
ssh_pswd: "wwpwcl44"

# Set the name of the client files to run
client_files:
  - "dgl_default.py"
  - "dgl_jpgnn_trans.py"
  - "dgl_jpgnn_trans_multiplenfs"
run_client_idx: 0 # Choose the client file to run

# training parameters
model_name: "gcn"
batch_size: 1000000
sampling: "2"
n_epochs: 10
cluster_build_port: "23456" # used by pytorch init_group
grpc_port: "18110"
dataset: "citeseer0" # WARNING: rewrite dataset item in ./dist/conf/static_cache.yaml

# statistic
log: True
eval: True

# Set the name of the server files to run
server_files:
  - "static_cache.yaml"
run_server_idx: 0 # Choose the client file to run
