# Set the IP addresses of the servers to deploy the cluster
# WARNING: rewrite cache_group item in ./dist/conf/static_cache.yaml
cluster_servers:
  # - "10.214.243.19" # yq2
  - "10.214.241.227" # yq4
  - "10.214.241.228" # yq5
  - "10.214.241.223" # yq6
  - "10.214.241.232" # yq7

# sshinfo
ssh_pswd: "wwpwcl44"

# Set the name of the client files to run
client_files:
  - "dgl_default.py" # 原始的 GNN 训练
  - "dgl_jpgnn_trans.py" # 基于 MB 的模型迁移 GNN 训练
  - "dgl_jpgnn_trans_multiplenfs.py" # 合并子树并去重
  - "dgl_jpgnn_trans_lessjp.py" # 减少跳跃的机器数量
  - "dgl_p3.py"
  - "dgl_p3_avoid_oom.py"
  - "dgl_jpgnn_trans_lessjp_avoid_error.py"
  - "dgl_default_localshuffle.py" # 原始的 GNN 训练 - localshuffle 版本
# Choose the client file to run
run_client_idx: 0

# training parameters
model_name: "gcn"
batch_size: 4096
sampling: "2"
n_epochs: 50
learning_rate: 0.03
cluster_build_port: "23457" # used by pytorch init_group
grpc_port: "18116" # used for communication of cache server and client
dataset: "ogbn_arxiv0" # WARNING: rewrite dataset item in ./dist/conf/static_cache.yaml; choices=['reddit0', 'ogbn_arxiv0', 'ogbn_products0']
hidden_size: 256

# statistic
log: True # rewrite statistic item in static_cache.yaml
# log: False
eval: True
# eval: False

# Set the name of the server files to run
server_files:
  - "static_cache.yaml"
run_server_idx: 0 # Choose the client file to run
cache_type: "static" # rewrite cache_type in static_cache.yaml file ['p3', 'static']
multi_feat_file: false # each part has one feat file
partition_type: "metis" # [metis, pg]
