# Set the IP addresses of the servers to deploy the cluster
# WARNING: rewrite cache_group item in ./dist/conf/static_cache.yaml
cluster_servers:
  - "10.214.243.19" # yq2
  - "10.214.241.227" # yq4
  - "10.214.241.228" # yq5
  - "10.214.241.229" # yq6

# sshinfo
ssh_pswd: "wwpwcl44"

# Set the name of the client files to run
client_files:
  - "dgl_default.py" # 原始的 GNN 训练
  - "dgl_jpgnn_trans.py" # 基于 MB 的模型迁移 GNN 训练
  - "dgl_jpgnn_trans_multiplenfs.py" # 合并子树并去重
  - "dgl_jpgnn_trans_lessjp.py" # 减少跳跃的机器数量
run_client_idx: 3 # Choose the client file to run

# training parameters
model_name: "gcn"
batch_size: 1000
sampling: "2-2"
n_epochs: 5
cluster_build_port: "23456" # used by pytorch init_group
grpc_port: "18110"
dataset: "ogbn_arxiv128" # WARNING: rewrite dataset item in ./dist/conf/static_cache.yaml

# statistic
log: True
eval: False

# Set the name of the server files to run
server_files:
  - "static_cache.yaml"
run_server_idx: 0 # Choose the client file to run
