# Set the IP addresses of the servers to deploy the cluster
# WARNING: rewrite cache_group item in ./dist/conf/static_cache.yaml
cluster_servers:
  # - "10.214.243.19" # yq2
  # - "10.214.241.227" # yq4
  # - "10.214.241.228" # yq5
  # - "10.214.241.223" # yq6
  # - "10.214.241.232" # yq7
  - "12.12.12.4" # yq4
  - "12.12.12.3" # yq5
  - "12.12.12.2" # yq6
  - "12.12.12.1" # yq7
  # - "12.12.12.4" # yq4
  # - "12.12.12.3" # yq5
  # - "12.12.12.5" # yq2
  # - "12.12.12.6" # yq8


# sshinfo
ssh_pswd: "wwpwcl44"

# Set the name of the client files to run
client_files:
  - "dgl_default.py" # 原始的 GNN 训练 0
  - "dgl_jpgnn_trans.py" # 基于 MB 的模型迁移 GNN 训练 1
  - "dgl_jpgnn_trans_multiplenfs.py" # 合并子树并去重 2
  - "dgl_jpgnn_trans_lessjp.py" # 减少跳跃的机器数量 3
  - "dgl_p3.py" # 4
  - "dgl_p3_avoid_oom.py" # 5
  - "dgl_jpgnn_trans_lessjp_avoid_error.py" # 6
  - "dgl_default_localshuffle.py" # 原始的 GNN 训练 - localshuffle 版本 7
  - "dgl_trans_naive.py" # 8
  - "dgl_default_avoid_oom.py" # 9
  - "dgl_jpgnn_trans_random_lessjp.py" # 10
  - "dgl_jpgnn_trans_multiplenfs_avoid_oom.py" # 11
  - "dgl_trans_naive_stop.py" # 12
  - "dgl_jpgnn_trans_avoid_oom.py" # 13
  - "multi/multi_dgl_default.py" # 14
  - "dgl_neutronstar_statistic.py" # 15
  # - "dgl_default_partialremotegather.py" # 原始的 GNN 训练 - 远程的节点只聚合部分 版本
# Choose the client file to run
run_client_idx: 4

# training parameters
model_name: "gat"
batch_size: 4096
sampling: "2-2"
n_epochs: 3
learning_rate: 0.001
cluster_build_port: "23451" # used by pytorch init_group
grpc_port: "18113" # used for communication of cache server and client
dataset: "ogbn_arxiv0" # WARNING: rewrite dataset item in ./dist/conf/static_cache.yaml; choices=['reddit0', 'ogbn_arxiv0', 'ogbn_products0']
hidden_size: 256

# statistic
log: True # rewrite statistic item in static_cache.yaml
# log: False
eval: False
# eval: False
gputil: False
utilinterval: 0.05
lb: False

# Set the name of the server files to run
server_files:
  - "static_cache.yaml"
run_server_idx: 0 # Choose the client file to run
cache_type: "static" # rewrite cache_type in static_cache.yaml file ['p3', 'static']
multi_feat_file: false # each part has one feat file
partition_type: "metis" # [metis, pg]

ssh_port: "2022"
