# ogbn-arxiv128 2layer
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 5 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 15 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 5 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 15 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 5 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 15 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 5 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 15 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 5 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 15 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
# ogbn-products 2layer
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 5 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 15 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 5 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 3 --sampling 15 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 5 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 15 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 5 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 15 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 5 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 15 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
ogbn-arxiv128 3layer
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 32 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 32 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 6 --sampling 10-10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 6 --sampling 10 -d ./dist/repgnn_data/ogbn_arxiv128/ -mn gcn --featdim 128
# ogbn-products 3layer
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 2 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 4 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 6 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 6 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 8 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 16 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 32 --sampling 10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100
time python3 simulate/obsv1/dgl_default_sampling_simulate.py -bs 1 -ep 1 --world-size 32 --sampling 10-10 -d ./dist/repgnn_data/ogbn_products0/ -mn gcn --featdim 100