# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distcache.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64istcache.proto\x12\x03rpc\"\x18\n\tDCRequest\x12\x0b\n\x03idx\x18\x01 \x01(\x03\"\x1a\n\x07\x44\x43Reply\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\x02\x32\x36\n\x08Operator\x12*\n\x08\x44\x43Submit\x12\x0e.rpc.DCRequest\x1a\x0c.rpc.DCReply\"\x00\x42\nZ\x08./;cacheb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distcache_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;cache'
  _DCREQUEST._serialized_start=24
  _DCREQUEST._serialized_end=48
  _DCREPLY._serialized_start=50
  _DCREPLY._serialized_end=76
  _OPERATOR._serialized_start=78
  _OPERATOR._serialized_end=132
# @@protoc_insertion_point(module_scope)
